### ISSUE TITLE
Fix reboot

### ISSUE THREAD

**Issue by moul** [scaleway/image-archlinux#5]
We experienced a kernel panic during a reboot, probably due to the `nbd` service in the stop sequence order.
If you encounter this behaviour, just click on `Hard reboot` on the web console.

**Comment by klausenbusk** [comment]
This is fixable, I was able to perform a manually "hacky" reboot of Arch Linux. When I was looking at ArchLinux some months ago.
First '--systemd-mark' need to be added to the cmdline, so nbd is killed as late as possible. It won't kernel panic, but it also won't boot. Because 'nbd' is killed before it got the chance to disconnect from our server.

ArchLinux as default automatically create a "initramfs" on shutdown. (https://lists.archlinux.org/pipermail/arch-dev-public/2013-December/025742.html)

I can't remember exactly what I did, but it was something like this:
```
/usr/bin/mkinitcpio -A shutdown -k none -c /dev/null -d /run/initramfs
nano /usr/lib/initcpio/install/shutdown
```
add the `nbd-client` binary and `nano /usr/lib/initcpio/shutdown`.. Where you should add `nbd-client -d /dev/???` somewhere :)

Sorry, it is back in October, I was looking at this.. Hope you get the idea..
http://www.freedesktop.org/wiki/Software/systemd/InitrdInterface/

**Comment by moul** [comment]
Thanks a lot for your feedback, actually we don't need to pass --systemd-mark on the cmdline, since we simulate its behaviour by using an "@" argv[0][0] (see https://github.com/online-labs/initrd/commit/51b4d034fef27f212a423a034a9d413601e495b7).
This initrd is not the one used on all bootscripts, but if you switch to the latest 3.2.34 bootscript and reboot, you should have it enabled.

---

About the initrd-like shutdown, I'm really interested and I will try to get it working, thanks a lot.
We thought that your solution is certainly the best, but we were blocked by only knowing a systemd-based solution (see https://github.com/online-labs/initrd/issues/31), your solution seems to be easier to setup on all distributions (systemd-based or not)

We will give a try next week

**Comment by moul** [comment]
@klausenbusk I have a proof of concept semi working thanks to your help: https://github.com/online-labs/initrd/compare/initrd-shutdown

Stay tuned, thanks again

**Comment by moul** [comment]
Fixed
